# Assignment 10:
### รหัสนักศึกษา: 67130700333
### ชื่อ-นามสกุล: Kijsarun Phromsen
### หลักสูตร: 67130700333

## bag-of-words model

1. สร้างตัวสกัดคุณลักษะข้อความแบบ bag of word โดยใช้  CountVectorizer()

In [3]:
from nltk import ConfusionMatrix
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
docs = np.array([
        'The sun is shining',
        'The weather is sweet',
        'The sun is shining, the weather is sweet, and one and one is two'])

count = CountVectorizer()

2. สกัดคุณลักษณะ ของข้อความ 3 ข้อความ ใน docs แล้วเก็บไว้ที่ bag

In [4]:
bag = count.fit_transform(docs)

3. แสดง คำศัพท์ ที่อยู่ในตัวสกัดคุณลักษณะ count โดยใช้ .vocabulary_ 

In [5]:
print(count.vocabulary_)

{'the': 6, 'sun': 4, 'is': 1, 'shining': 3, 'weather': 8, 'sweet': 5, 'and': 0, 'one': 2, 'two': 7}


4. แสดงลำดับชื่อ feature ที่อยู่ในตัวสกัดคุณลักษณะ โดยใช้  get_feature_names_out()

In [6]:
print(count.get_feature_names_out())

['and' 'is' 'one' 'shining' 'sun' 'sweet' 'the' 'two' 'weather']


5. แสดง vector ของทั้ง 3 ข้อความ ที่เก็บอยู่ใน bag โดยแปลงเป็น array ก่อนแสดงผล โดยใช้ .toarray()

In [7]:
print(bag.toarray())

[[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [2 3 2 1 1 1 2 1 1]]


6. กำหนดให้ แถวและคอลัมน์ เริ่มที่ 0  

- จงอธิบายค่าที่ได้ใน แถวที่ 2 คอลัมนที่ 1 ซึ่งมีค่าเท่ากับ **3**  

**ตอบ** ค่าในเมทริกซ์จะบอกถึงความถี่ (Count) ที่คำ ๆ นั้นปรากฏในประโยคซึ่งการที่แถวที่ 2 หรือประโยคที่ 3 และคอลัมน์ที่ 1 หรือคำว่า "is" มีค่าเท่ากับ 3 หมายความว่าในประโยคที่ 3 มีคำว่า 'is' ปรากฏอยู่ทั้งหมด 3 ครั้ง

## Unigrams and Bigrams

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

corpus = np.array([
        'The sun is shining',
        'The weather is sweet',
        'The sun is shining, the weather is sweet, and one and one is two'])

docs = np.array([
        'The sun is shining',
        'The weather is sweet',
        'The sun is shining, the weather is sweet, and one and one is two'])


### Unigrams

In [9]:
vectorizer = CountVectorizer(ngram_range=(1, 1))
vectorizer.fit(corpus)

,"input input: {'filename', 'file', 'content'}, default='content'- If `'filename'`, the sequence passed as an argument to fit is expected to be a list of filenames that need reading to fetch the raw content to analyze.- If `'file'`, the sequence items must have a 'read' method (file-like object) that is called to fetch the bytes in memory.- If `'content'`, the input is expected to be a sequence of items that can be of type string or byte.",'content'
,"encoding encoding: str, default='utf-8'If bytes or files are given to analyze, this encoding is used todecode.",'utf-8'
,"decode_error decode_error: {'strict', 'ignore', 'replace'}, default='strict'Instruction on what to do if a byte sequence is given to analyze thatcontains characters not of the given `encoding`. By default, it is'strict', meaning that a UnicodeDecodeError will be raised. Othervalues are 'ignore' and 'replace'.",'strict'
,"strip_accents strip_accents: {'ascii', 'unicode'} or callable, default=NoneRemove accents and perform other character normalizationduring the preprocessing step.'ascii' is a fast method that only works on characters that havea direct ASCII mapping.'unicode' is a slightly slower method that works on any characters.None (default) means no character normalization is performed.Both 'ascii' and 'unicode' use NFKD normalization from:func:`unicodedata.normalize`.",None
,"lowercase lowercase: bool, default=TrueConvert all characters to lowercase before tokenizing.",True
,"preprocessor preprocessor: callable, default=NoneOverride the preprocessing (strip_accents and lowercase) stage whilepreserving the tokenizing and n-grams generation steps.Only applies if ``analyzer`` is not callable.",None
,"tokenizer tokenizer: callable, default=NoneOverride the string tokenization step while preserving thepreprocessing and n-grams generation steps.Only applies if ``analyzer == 'word'``.",None
,"stop_words stop_words: {'english'}, list, default=NoneIf 'english', a built-in stop word list for English is used.There are several known issues with 'english' and you shouldconsider an alternative (see :ref:`stop_words`).If a list, that list is assumed to contain stop words, all of whichwill be removed from the resulting tokens.Only applies if ``analyzer == 'word'``.If None, no stop words will be used. In this case, setting `max_df`to a higher value, such as in the range (0.7, 1.0), can automatically detectand filter stop words based on intra corpus document frequency of terms.",None
,"token_pattern token_pattern: str or None, default=r""(?u)\\b\\w\\w+\\b""Regular expression denoting what constitutes a ""token"", only usedif ``analyzer == 'word'``. The default regexp select tokens of 2or more alphanumeric characters (punctuation is completely ignoredand always treated as a token separator).If there is a capturing group in token_pattern then thecaptured group content, not the entire match, becomes the token.At most one capturing group is permitted.",'(?u)\\b\\w\\w+\\b'
,"ngram_range ngram_range: tuple (min_n, max_n), default=(1, 1)The lower and upper boundary of the range of n-values for differentword n-grams or char n-grams to be extracted. All values of n suchsuch that min_n <= n <= max_n will be used. For example an``ngram_range`` of ``(1, 1)`` means only unigrams, ``(1, 2)`` meansunigrams and bigrams, and ``(2, 2)`` means only bigrams.Only applies if ``analyzer`` is not callable.","(1, ...)"
,"analyzer analyzer: {'word', 'char', 'char_wb'} or callable, default='word'Whether the feature should be made of word n-gram or charactern-grams.Option 'char_wb' creates character n-grams only from text insideword boundaries; n-grams at the edges of words are padded with space.If a callable is passed it is used to extract the sequence of featuresout of the raw, unprocessed input... versionchanged:: 0.21Since v0.21, if ``input`` is ``filename`` or ``file``, the data isfirst read from the file and then passed to the given callableanalyzer.",'word'


In [10]:
X = vectorizer.transform(corpus)

In [11]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 17 stored elements and shape (3, 9)>
  Coords	Values
  (0, 1)	1
  (0, 3)	1
  (0, 4)	1
  (0, 6)	1
  (1, 1)	1
  (1, 5)	1
  (1, 6)	1
  (1, 8)	1
  (2, 0)	2
  (2, 1)	3
  (2, 2)	2
  (2, 3)	1
  (2, 4)	1
  (2, 5)	1
  (2, 6)	2
  (2, 7)	1
  (2, 8)	1


In [12]:
print(X.toarray())
print(vectorizer.get_feature_names_out())

[[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [2 3 2 1 1 1 2 1 1]]
['and' 'is' 'one' 'shining' 'sun' 'sweet' 'the' 'two' 'weather']


### Bigrams

In [13]:
vectorizer = CountVectorizer(ngram_range=(2, 2))
vectorizer.fit(corpus)

,"input input: {'filename', 'file', 'content'}, default='content'- If `'filename'`, the sequence passed as an argument to fit is expected to be a list of filenames that need reading to fetch the raw content to analyze.- If `'file'`, the sequence items must have a 'read' method (file-like object) that is called to fetch the bytes in memory.- If `'content'`, the input is expected to be a sequence of items that can be of type string or byte.",'content'
,"encoding encoding: str, default='utf-8'If bytes or files are given to analyze, this encoding is used todecode.",'utf-8'
,"decode_error decode_error: {'strict', 'ignore', 'replace'}, default='strict'Instruction on what to do if a byte sequence is given to analyze thatcontains characters not of the given `encoding`. By default, it is'strict', meaning that a UnicodeDecodeError will be raised. Othervalues are 'ignore' and 'replace'.",'strict'
,"strip_accents strip_accents: {'ascii', 'unicode'} or callable, default=NoneRemove accents and perform other character normalizationduring the preprocessing step.'ascii' is a fast method that only works on characters that havea direct ASCII mapping.'unicode' is a slightly slower method that works on any characters.None (default) means no character normalization is performed.Both 'ascii' and 'unicode' use NFKD normalization from:func:`unicodedata.normalize`.",None
,"lowercase lowercase: bool, default=TrueConvert all characters to lowercase before tokenizing.",True
,"preprocessor preprocessor: callable, default=NoneOverride the preprocessing (strip_accents and lowercase) stage whilepreserving the tokenizing and n-grams generation steps.Only applies if ``analyzer`` is not callable.",None
,"tokenizer tokenizer: callable, default=NoneOverride the string tokenization step while preserving thepreprocessing and n-grams generation steps.Only applies if ``analyzer == 'word'``.",None
,"stop_words stop_words: {'english'}, list, default=NoneIf 'english', a built-in stop word list for English is used.There are several known issues with 'english' and you shouldconsider an alternative (see :ref:`stop_words`).If a list, that list is assumed to contain stop words, all of whichwill be removed from the resulting tokens.Only applies if ``analyzer == 'word'``.If None, no stop words will be used. In this case, setting `max_df`to a higher value, such as in the range (0.7, 1.0), can automatically detectand filter stop words based on intra corpus document frequency of terms.",None
,"token_pattern token_pattern: str or None, default=r""(?u)\\b\\w\\w+\\b""Regular expression denoting what constitutes a ""token"", only usedif ``analyzer == 'word'``. The default regexp select tokens of 2or more alphanumeric characters (punctuation is completely ignoredand always treated as a token separator).If there is a capturing group in token_pattern then thecaptured group content, not the entire match, becomes the token.At most one capturing group is permitted.",'(?u)\\b\\w\\w+\\b'
,"ngram_range ngram_range: tuple (min_n, max_n), default=(1, 1)The lower and upper boundary of the range of n-values for differentword n-grams or char n-grams to be extracted. All values of n suchsuch that min_n <= n <= max_n will be used. For example an``ngram_range`` of ``(1, 1)`` means only unigrams, ``(1, 2)`` meansunigrams and bigrams, and ``(2, 2)`` means only bigrams.Only applies if ``analyzer`` is not callable.","(2, ...)"
,"analyzer analyzer: {'word', 'char', 'char_wb'} or callable, default='word'Whether the feature should be made of word n-gram or charactern-grams.Option 'char_wb' creates character n-grams only from text insideword boundaries; n-grams at the edges of words are padded with space.If a callable is passed it is used to extract the sequence of featuresout of the raw, unprocessed input... versionchanged:: 0.21Since v0.21, if ``input`` is ``filename`` or ``file``, the data isfirst read from the file and then passed to the given callableanalyzer.",'word'


In [14]:
X = vectorizer.transform(corpus)

In [15]:
print(X.toarray())
print(vectorizer.get_feature_names_out())

[[0 1 0 0 0 0 0 1 0 1 0 0]
 [0 0 1 0 0 0 0 0 0 0 1 1]
 [2 1 1 1 1 1 1 1 1 1 1 1]]
['and one' 'is shining' 'is sweet' 'is two' 'one and' 'one is'
 'shining the' 'sun is' 'sweet and' 'the sun' 'the weather' 'weather is']


### Unigrams + Bigrams

In [16]:
vectorizer = CountVectorizer(ngram_range=(1, 2))
vectorizer.fit(corpus)

,"input input: {'filename', 'file', 'content'}, default='content'- If `'filename'`, the sequence passed as an argument to fit is expected to be a list of filenames that need reading to fetch the raw content to analyze.- If `'file'`, the sequence items must have a 'read' method (file-like object) that is called to fetch the bytes in memory.- If `'content'`, the input is expected to be a sequence of items that can be of type string or byte.",'content'
,"encoding encoding: str, default='utf-8'If bytes or files are given to analyze, this encoding is used todecode.",'utf-8'
,"decode_error decode_error: {'strict', 'ignore', 'replace'}, default='strict'Instruction on what to do if a byte sequence is given to analyze thatcontains characters not of the given `encoding`. By default, it is'strict', meaning that a UnicodeDecodeError will be raised. Othervalues are 'ignore' and 'replace'.",'strict'
,"strip_accents strip_accents: {'ascii', 'unicode'} or callable, default=NoneRemove accents and perform other character normalizationduring the preprocessing step.'ascii' is a fast method that only works on characters that havea direct ASCII mapping.'unicode' is a slightly slower method that works on any characters.None (default) means no character normalization is performed.Both 'ascii' and 'unicode' use NFKD normalization from:func:`unicodedata.normalize`.",None
,"lowercase lowercase: bool, default=TrueConvert all characters to lowercase before tokenizing.",True
,"preprocessor preprocessor: callable, default=NoneOverride the preprocessing (strip_accents and lowercase) stage whilepreserving the tokenizing and n-grams generation steps.Only applies if ``analyzer`` is not callable.",None
,"tokenizer tokenizer: callable, default=NoneOverride the string tokenization step while preserving thepreprocessing and n-grams generation steps.Only applies if ``analyzer == 'word'``.",None
,"stop_words stop_words: {'english'}, list, default=NoneIf 'english', a built-in stop word list for English is used.There are several known issues with 'english' and you shouldconsider an alternative (see :ref:`stop_words`).If a list, that list is assumed to contain stop words, all of whichwill be removed from the resulting tokens.Only applies if ``analyzer == 'word'``.If None, no stop words will be used. In this case, setting `max_df`to a higher value, such as in the range (0.7, 1.0), can automatically detectand filter stop words based on intra corpus document frequency of terms.",None
,"token_pattern token_pattern: str or None, default=r""(?u)\\b\\w\\w+\\b""Regular expression denoting what constitutes a ""token"", only usedif ``analyzer == 'word'``. The default regexp select tokens of 2or more alphanumeric characters (punctuation is completely ignoredand always treated as a token separator).If there is a capturing group in token_pattern then thecaptured group content, not the entire match, becomes the token.At most one capturing group is permitted.",'(?u)\\b\\w\\w+\\b'
,"ngram_range ngram_range: tuple (min_n, max_n), default=(1, 1)The lower and upper boundary of the range of n-values for differentword n-grams or char n-grams to be extracted. All values of n suchsuch that min_n <= n <= max_n will be used. For example an``ngram_range`` of ``(1, 1)`` means only unigrams, ``(1, 2)`` meansunigrams and bigrams, and ``(2, 2)`` means only bigrams.Only applies if ``analyzer`` is not callable.","(1, ...)"
,"analyzer analyzer: {'word', 'char', 'char_wb'} or callable, default='word'Whether the feature should be made of word n-gram or charactern-grams.Option 'char_wb' creates character n-grams only from text insideword boundaries; n-grams at the edges of words are padded with space.If a callable is passed it is used to extract the sequence of featuresout of the raw, unprocessed input... versionchanged:: 0.21Since v0.21, if ``input`` is ``filename`` or ``file``, the data isfirst read from the file and then passed to the given callableanalyzer.",'word'


In [17]:
X = vectorizer.transform(corpus)

In [18]:
print(X.toarray())
print(vectorizer.get_feature_names_out())

[[0 0 1 1 0 0 0 0 0 1 0 1 1 0 0 1 1 0 0 0 0]
 [0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1]
 [2 2 3 1 1 1 2 1 1 1 1 1 1 1 1 2 1 1 1 1 1]]
['and' 'and one' 'is' 'is shining' 'is sweet' 'is two' 'one' 'one and'
 'one is' 'shining' 'shining the' 'sun' 'sun is' 'sweet' 'sweet and' 'the'
 'the sun' 'the weather' 'two' 'weather' 'weather is']


## Term frequency-inverse document frequency

0. เตรียม vector bag of words สำหรับแปลงเป็น tfidf

In [19]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

np.set_printoptions(precision=2)
docs = np.array([
        'The sun is shining',
        'The weather is sweet',
        'The sun is shining, the weather is sweet, and one and one is two'])

count = CountVectorizer()
bag = count.fit_transform(docs)

print("Words: \n",count.get_feature_names_out())
print("BOW: \n", bag.toarray() )

Words: 
 ['and' 'is' 'one' 'shining' 'sun' 'sweet' 'the' 'two' 'weather']
BOW: 
 [[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [2 3 2 1 1 1 2 1 1]]


In [20]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer(use_idf=True, norm= None, smooth_idf=True)

2. แปลงคุณลักณะ bag เป็น tfidf โดยใช้ .fit_transform() แล้วเก็บไว้ที่ตัวแปร V_tfidf

In [21]:
V_tfidf =tfidf.fit_transform(bag)

3. แสดงเวกเตอร์ tfidf ที่ได้ในรูปแบบของ array โดยใช้ .toarray()

In [22]:
print("Words: \n",count.get_feature_names_out())
print("TF-IDF: \n", V_tfidf.toarray())

Words: 
 ['and' 'is' 'one' 'shining' 'sun' 'sweet' 'the' 'two' 'weather']
TF-IDF: 
 [[0.   1.   0.   1.29 1.29 0.   1.   0.   0.  ]
 [0.   1.   0.   0.   0.   1.29 1.   0.   1.29]
 [3.39 3.   3.39 1.29 1.29 1.29 2.   1.69 1.29]]


4. กำหนดให้ แถวและคอลัมน์ เริ่มที่ 0 
- จงอธิบายค่าที่ได้ ในแถวที่ 2 คอมลัมน์ที่ 7 ซึ่งมีค่าเท่ากับ 1.69
- แสดงการคำนวณค่าดังกล่าว

**ตอบ**
#### อธิบายค่าที่ได้ ในแถวที่ 2 คอมลัมน์ที่ 7 ซึ่งมีค่าเท่ากับ 1.69
ค่า 1.69 ใน row ที่ 2 columns ที่ 7 ใช้บอกโมเดลว่าคำว่า "two" เป็นคำสำคัญ (Keyword) ที่ใช้เป็นเอกลักษณ์เพื่อแยกแยะประโยคที่ 3 ออกจากประโยคอื่น ๆ ได้เป็นอย่างดี เนื่องจากคำว่า two โผล่มาแค่ในประโยคนี้ประโยคเดียว

#### แสดงการคำนวณค่าดังกล่าว
ขั้นตอนที่ 1: หาค่า TF (Term Frequency)
ดูว่าคำว่า two โผล่มาในประโยคนี้กี่ครั้ง
คำว่า "two" ปรากฏในประโยคที่ 3 จำนวน $1$ ครั้ง -> ค่า TF เท่ากับ 1
#### -------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ขั้นตอนที่ 2: ประเมินว่าคำนี้หายากแค่ไหนจากประโยคทั้งหมดจากสูตร:
$$IDF = \ln(\frac{N + 1}{df + 1}) + 1$$

$N$ (จำนวนประโยคทั้งหมด) = $3$ ประโยค และ $df$ (Document Frequency หรือ จำนวนประโยคที่มีคำว่า "two" ซ่อนอยู่) = $1$ ประโยค (เจอแค่ในประโยคที่ 3 เท่านั้น)

แทนค่าลงในสมการ:
$$IDF = \ln(\frac{3 + 1}{1 + 1}) + 1$$$$IDF = \ln(\frac{4}{2}) + 1$$$$IDF = \ln(2) + 1$$$$IDF \approx 0.693 + 1 = 1.693$$

#### -------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ขั้นตอนที่ 3: นำค่าที่ได้มาคูณกัน
$$TF\text{-}IDF = TF \times IDF$$$$TF\text{-}IDF = 1 \times 1.693 = 1.693$$

5. เขียนโค้ด ทำ normalize โดยการหารด้วยขนาดของเวกเตอร์แบบ l2 หรือ euclidean norm

In [23]:
raw_tfidf = V_tfidf.toarray()[0]
l2_tfidf = raw_tfidf / np.sqrt(np.sum(raw_tfidf**2))
l2_tfidf

array([0.  , 0.43, 0.  , 0.56, 0.56, 0.  , 0.43, 0.  , 0.  ])

### Normalization tfidf

In [24]:
docs = np.array([
        'The sun is shining',
        'The weather is sweet',
        'The sun is shining, the weather is sweet, and one and one is two'])


1. สร้างตัวแปลงคุณลักษณะเป็น tfidf โดยกำหนดให้ norm= 'l2' และ smooth_idf=True

In [25]:
from sklearn.feature_extraction.text import TfidfTransformer

count = CountVectorizer()
bag = count.fit_transform(docs)

tfidf = TfidfTransformer(use_idf=True, norm='l2' , smooth_idf=True)
V_tfidf = tfidf.fit_transform(bag)

print("TF-IDF: \n", V_tfidf.toarray())

TF-IDF: 
 [[0.   0.43 0.   0.56 0.56 0.   0.43 0.   0.  ]
 [0.   0.43 0.   0.   0.   0.56 0.43 0.   0.56]
 [0.5  0.45 0.5  0.19 0.19 0.19 0.3  0.25 0.19]]


2. สกัดคุณลักษณะ โดยใช้ TfidfVectorizer โดยส่งค่า docs ไปทำงาน

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf2 = TfidfVectorizer(use_idf=True, norm= 'l2', smooth_idf=True)
V_tfidf2 = tfidf2.fit_transform(docs)

print("TF-IDF: \n", V_tfidf2.toarray())

TF-IDF: 
 [[0.   0.43 0.   0.56 0.56 0.   0.43 0.   0.  ]
 [0.   0.43 0.   0.   0.   0.56 0.43 0.   0.56]
 [0.5  0.45 0.5  0.19 0.19 0.19 0.3  0.25 0.19]]


## Cleaning text data

0. สร้างฟังก์ชันสำหรับทำความสะอาดข้อความ

In [27]:
import re
def preprocess(text):
    text = re.sub('<[^>]*>', '', text)
    emoticons = re.findall(r'(?::|;|=)(?:-)?(?:\)|\(|D|P)',text)
    text = (re.sub(r'[\W]+', ' ', text.lower()) +
            ' '.join(emoticons).replace('-', ''))
    return text

In [28]:
reviews = np.array(['My vote is seven.<br /><br />Title (Brazil): Not Available', 
           '</a>This :) is :( a test :-)!'])

1. ทำความสะอาดข้อความ ใน reviews[0]

In [29]:
reviews[0]

'My vote is seven.<br /><br />Title (Brazil): Not Available'

In [30]:
preprocess(reviews[0])

'my vote is seven title brazil not available'

2. ทำความสะอาดข้อความ ใน reviews[1]

In [31]:
reviews[1]

'</a>This :) is :( a test :-)!'

In [32]:
preprocess(reviews[1])

'this is a test :) :( :)'

3. กำจัด stopwords และ ทำความสะอาดด้วย preprocess

In [33]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\UsEr\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [34]:
from nltk.corpus import stopwords
stop = stopwords.words('english')

cnt = CountVectorizer(stop_words=stop, preprocessor=preprocess)
print(cnt.fit_transform(reviews).toarray())
print(cnt.get_feature_names_out(reviews))

[[1 1 1 0 1 1]
 [0 0 0 1 0 0]]
['available' 'brazil' 'seven' 'test' 'title' 'vote']


4. กำหนดแถวเริ่มที่ 0 
-อธิบายค่าที่ได้ในข้อ 3 ในแถวที่ 1 ซึ่งเท่ากับ  [0 0 0 1 0 0] 

**ตอบ** ตัวเลขภายในที่ 2 ใช้ในการบอก model ว่าภายในประโยคที่ 2 มีคำว่า test ปรากฏอยู่เพียง 1 ครั้ง ส่วนคำอื่น ๆ ได้แก่ 'available', 'brazil', 'seven', 'title', 'vote' ไม่มีปรากฏอยู่ภายในประโยคที่ 2 เลย

## สร้างโมเดล logistic regression model สำหรับจำแนกข้อความ  

1. อ่านไฟล์ movie_data.csv

In [35]:
import pandas as pd

df = pd.read_csv('movie_data.csv', encoding='utf-8')
df.head(3)

,review,sentiment
0,"In 1974, the teenager Martha Moxley (Maggie Gr...",1
1,OK... so... I really like Kris Kristofferson a...,0
2,"***SPOILER*** Do not read this, if you think a...",0


2. สร้างคำหยุด จากคำหยุดมาตรฐานในภาษาอังกฤษ 'english' เก็บไว้ในตัวแปร stop

In [36]:
from nltk.corpus import stopwords
stop = stopwords.words('english')

3. สร้างฟังก์ทำความสะอาดข้อความ ชื่อฟังก์ชัน TextClaen

In [2]:
import re
def TextClean (text):
    text = re.sub('<[^>]*>', '', text)
    emoticons = re.findall(r'(?::|;|=)(?:-)?(?:\)|\(|D|P)',
                           text)
    text = (re.sub(r'[\W]+', ' ', text.lower()) +
            ' '.join(emoticons).replace('-', ''))
    return text

4. แบ่งชุดข้อมูล train และ test โดย train คือ  25000 ข้อความแรก และ test คือ  25000 ข้อความหลัง 

In [38]:
X_train = df.loc[:25000]['review'].values
y_train = df.loc[:25000]['sentiment'].values
X_test = df.loc[25000:]['review'].values
y_test = df.loc[25000:]['sentiment'].values

5. สร้างรูปแบบตัวสกัดคุณลักษณะ ด้วย TfidfVectorizer

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(use_idf=True, norm= 'l2', smooth_idf=True,stop_words=stop, preprocessor=TextClean)

6. fit และ transform ตัวสกัดคุณลักษณะบนข้อมูล X_train เก็บไว้ที่ตัวแปร V_train

In [40]:
V_train = tfidf.fit_transform(X_train)

7. transform ตัวสกัดคุณลักษณะบนข้อมูล X_test เก็บไว้ที่ตัวแปร V_test

In [41]:
V_test = tfidf.transform(X_test)

8. สร้างโมเดลจำแนกโดยใช้ LogisticRegression

In [42]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0, solver='liblinear')

9. สอนโมเดลด้วยชุดข้อมูลสอน V_train,y_train

In [43]:
clf.fit(V_train,y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",0
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`multic

10. ทำนาย ด้วยชุดข้อมูลทดสอบ V_test

In [44]:
y_pred = clf.predict(V_test)

11. หาค่า confusion matrix , accuracy , precision, recall, f1

In [45]:
from sklearn.metrics import classification_report, confusion_matrix
cfm = confusion_matrix(y_test,y_pred)
summary_eval = classification_report(y_test,y_pred)
print(cfm)
print(summary_eval)

[[11060  1467]
 [ 1209 11264]]
              precision    recall  f1-score   support

           0       0.90      0.88      0.89     12527
           1       0.88      0.90      0.89     12473

    accuracy                           0.89     25000
   macro avg       0.89      0.89      0.89     25000
weighted avg       0.89      0.89      0.89     25000



12. บันทึกโมเดลและค่าที่จะนำไปใช้ imdb-senti-xxx.pckl เมื่อ xxx แทนรหัสนักศึกษา

In [46]:
import pickle

f = open('imdb-senti-67130700333.pckl', 'wb')
pickle.dump([tfidf,clf,TextClean], f)
f.close()

13. ให้กด restart kernel แล้ว load ค่าจาก imdb-senti-xxx.pckl  

In [3]:
import pickle
f = open('imdb-senti-67130700333.pckl', 'rb')
tfidf,clf,preprocessor = pickle.load(f)
f.close()

14. สร้างข้อความโดย copy มาจาก imdb ที่เป็นข้อควาที่ให้ rating ไม่เกิน 3 แล้วทำนาย

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd 

text1 = "It was ok but ultimately a bit dull with lots of glaring plot holes and weird music. Didn't know if it wanted to be Interstellar or ET. I don't really get why people liked it so much. Ryan Gosling's performance was good but not enough to carry the whole movie. Ultimately I wouldn't recommend it myself."

if clf.predict(tfidf.transform([text1])) == 0:
    print('Negative')
else:
    print('Positive')
    

Negative


15. สร้างข้อความโดย copy มาจาก imdb ที่เป็นข้อควาที่ให้ rating เกิน 7 แล้วทำนาย

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd 

text2 = """I rarely write reviews on this site. But as this is an adaptation of one of my favorite novels of recent times, this was necessary.

Being a Big fan of the novel (reading the book 3 times), and one of my favorite novels of all time, What can I say? A masterpiece of adaptation. With a talented screenwriter like Drew Goddard adapting the work and talented directors like Lord and Miller, I already imagined it would be at least great.

Ryan Gosling was perfect in the role. This film will be nominated for several awards, it will be nominated for several Oscars, and Gosling will probably be nominated for best actor.

Ther score of Daniel Pemberton (Spiderverse 1 2 3) is sublime, like a Vangelis score type, Greig Fraser (Dune parts 1 2) Cinematography it´s top notch, Charles Wood Design (from many MCU films) it´s out of this World. The effects are perfect, but for a certain character most of them (for the happyness of me and many fans ) they are made of practical effects and I always thought that was the right way to create them. Who read or watched the movie knows who I am talking about.

Of course like in every adaptation, some things are removed, like some characters and scenes, but the main plot of course is here, and is faithful.

This is a great year for sci-fi fans. Project Hail Mary adaptation, Disclosure Day from Spielberg (his return to directing aliens), Dune Part 3 from Villeneuve.

I feel that Project Hail Mary will be one of the films with the most Oscar nominations in 2027, along with Christopher Nolan's Odyssey. But I hope it's time for the first alien and space film to win best picture, director, and screenplay."""

if clf.predict(tfidf.transform([text2])) == 0:
    print('Negative')
else:
    print('Positive')
    

Positive


## Thai Text

In [7]:
pip install --upgrade pip

  Using cached pip-26.0.1-py3-none-any.whl.metadata (4.7 kB)
Using cached pip-26.0.1-py3-none-any.whl (1.8 MB)
  Attempting uninstall: pip
    Found existing installation: pip 25.1.1
    Uninstalling pip-25.1.1:
      Successfully uninstalled pip-25.1.1
Note: you may need to restart the kernel to use updated packages.


In [8]:
pip install attacut

Note: you may need to restart the kernel to use updated packages.


In [9]:
from attacut import tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

In [10]:
tokenize('ฉันหิวข้าว')

['ฉัน', 'หิว', 'ข้าว']

In [11]:
Xtrain = ['“บิ๊กตู่” ให้กำลังใจ จนท.บำราศนราดูร ขอหนักนิดเบาหน่อยพูดกันดีๆ พร้อมปรับแก้',
          'รัฐบาลไฟเขียวต่ออายุราชการ อธิบดีกรมอุทยานแห่งชาติฯ อีก 1 ปี',
          '“บิ๊กป้อม” รับปากเคลียร์ “สิระ-ไผ่” ปะทะเดือดไลน์ พปชร.ยันทำงานกับ ปชป.ได้',
          'จ่อเซ็นแมนฯยู!! “จู๊ด เบลลิงแฮม” วันเดอร์คิดเบอร์มิงแฮม พร้อมครอบครัวบุกสนามซ้อมแคร์ริงตัน',
          '“จิ้งจอก” เลิกบู่ “วาร์ดี-บาร์นส” คนละ 2 เม็ด ถลุงวิลล่ายับ 4-0',
          '“ลิเวอร์พูล” นับถอยหลัง 5 วัน ฉลองแชมป์ที่บ้าน “เอฟเวอร์ตัน”'
          ]
Ytrain = ['การเมือง',
          'การเมือง',
          'การเมือง',
          'กีฬา',
          'กีฬา',
          'กีฬา'
          ]
Xtest = ['“อิทธิพล” ยัน คน พปชร.พี่น้องกัน เคลียร์กันได้ หลังไลน์เดือดปมหน้ากาก',
         '“บิ๊กป้อม” รับปากเคลียร์ “สิระ-ไผ่” ปะทะเดือดไลน์ พปชร.ยันทำงานกับ ปชป.ได้',
         '“ลิเวอร์พูล” นับถอยหลัง 5 วัน ฉลองแชมป์ที่บ้าน “เอฟเวอร์ตัน”',
         'เงินเหลือๆ “ฟลอยด์” ปล่อยวาทะเด็ดพร้อมฮุบกิจการ “นิวคาสเซิล”']

In [12]:
vectorizer = TfidfVectorizer(ngram_range=(1, 1), tokenizer=tokenize)

In [13]:
V_train = vectorizer.fit_transform(Xtrain)

C:\Users\UsEr\Desktop\Master Degree\Y2Sem2\ML\.venv\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [14]:
vectorizer.get_feature_names_out()

array([' ', ' “', '!', '-', '-บาร์นส', '0', '1', '2', '4', '5',
       'กรมอุทยานแห่ง', 'กัน', 'กับ', 'กำลังใจ', 'ขอ', 'คน', 'ครอบครัว',
       'คิด', 'งาน', 'จนท.บำราศนราดูร', 'จิ้งจอก”', 'จู๊ด เบลลิงแฮม',
       'จ่อ', 'ฉลอง', 'ชาติ', 'ซ้อมแคร์', 'ดี', 'ตัน', 'ต่อ', 'ถลุง',
       'ถอย', 'ทำ', 'ที่', 'นับ', 'นิดเบา', 'บิ๊กตู่', 'บิ๊กป้อม', 'บุก',
       'บู่', 'บ้าน', 'ปชป.', 'ปรับ', 'ปะทะ', 'ปี', 'พปชร.', 'พร้อม',
       'พูด', 'ยัน', 'ยับ', 'รัฐบาล', 'รับปาก', 'ราชการ', 'ริงตัน', 'ละ',
       'ลิเวอร์พู', 'ล”', 'วัน', 'วันเดอร์', 'วาร์ดี', 'วิลล่า', 'สนาม',
       'สิระ', 'หนัก', 'หน่อย', 'หลัง', 'อธิบดี', 'อายุ', 'อีก', 'ฯ',
       'เคลียร์', 'เซ็นแมนฯยู', 'เดือดไลน์', 'เบอร์มิงแฮม', 'เม็ด',
       'เลิก', 'เอฟเวอร์', 'แก้', 'แชมป์', 'ให้', 'ได้', 'ไผ่”',
       'ไฟเขียว', 'ๆ', '“', '”'], dtype=object)

In [16]:
V_test = vectorizer.transform(Xtest)

1. สร้างโมเดลจำแนกข้อความ ว่าเป็น หัวข้อข่าวการเมือง หรือกีฬา

In [17]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(random_state=0, solver='liblinear')
lr.fit(V_train, Ytrain)

y_pred = lr.predict(V_test)

2. แสดงการทดสอบโมเดล

In [20]:
results = pd.DataFrame({
    'ข้อความข่าว': Xtest,
    'ผลทำนาย (Category)': y_pred
})

display(results)

,ข้อความข่าว,ผลทำนาย (Category)
0,“อิทธิพล” ยัน คน พปชร.พี่น้องกัน เคลียร์กันได้...,การเมือง
1,“บิ๊กป้อม” รับปากเคลียร์ “สิระ-ไผ่” ปะทะเดือดไ...,การเมือง
2,“ลิเวอร์พูล” นับถอยหลัง 5 วัน ฉลองแชมป์ที่บ้าน...,กีฬา
3,เงินเหลือๆ “ฟลอยด์” ปล่อยวาทะเด็ดพร้อมฮุบกิจกา...,การเมือง


## Review Shopping

สร้างโมเดลโดยใช้ข้อมูลจาก review_shopping.csv และ Deploy model บน Streamlit

โดยสร้างอย่างน้อย 2 โมเดล และเลือกที่ดีกว่ามา Deploy

In [39]:
def thai_tokenize(text):
    return tokenize(text)

In [40]:
rv_data = pd.read_csv('review_shopping.csv', sep='\t', header=None, names=['text', 'sentiment'])
rv_data.head()

,text,sentiment
0,เกลียด ชอบหลอกให้สั่งซื้อ ที่ไหนได้ไม่มีสิ้นค้า,neg
1,สินค้าด้อยคุณภาพ,neg
2,สินค้าหมดทำไมไม่แจ้งขึ้นว่าหมดอะ.กดใส่ตะกร้าไป...,neg
3,อย่าทำแบบนี้กับใครอีกนะค่ะแย่มากค่ะ,neg
4,คือเเบบผิดหวังมาก เเย่ที่สุดได้ของมาฝาเเตก เเต...,neg


In [41]:
vectorizer = TfidfVectorizer(tokenizer=thai_tokenize, ngram_range=(1, 2))

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(rv_data['text'], rv_data['sentiment'], test_size=0.2, random_state=42)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

C:\Users\UsEr\Desktop\Master Degree\Y2Sem2\ML\.venv\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [46]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.naive_bayes import MultinomialNB

rv_lr = LogisticRegression(random_state=42, solver='liblinear')
rv_lr.fit(X_train_vec, y_train)

y_pred = rv_lr.predict(X_test_vec)

In [47]:
score_lr = rv_lr.score(X_test_vec, y_test)

rv_cfm = confusion_matrix(y_test, y_pred)
rv_sum = classification_report(y_test, y_pred)

print(rv_cfm)
print(rv_sum)
print(f"✅ Accuracy (with Attacut): {score_lr:.4f}")

[[12  1]
 [ 2 11]]
              precision    recall  f1-score   support

         neg       0.86      0.92      0.89        13
         pos       0.92      0.85      0.88        13

    accuracy                           0.88        26
   macro avg       0.89      0.88      0.88        26
weighted avg       0.89      0.88      0.88        26

✅ Accuracy (with Attacut): 0.8846


In [48]:
multi_nb = MultinomialNB()
multi_nb.fit(X_train_vec, y_train)
y_pred = multi_nb.predict(X_test_vec)

In [51]:
mnb_score = multi_nb.score(X_test_vec, y_test)

mnb_cfm = confusion_matrix(y_test, y_pred)
mnb_sum = classification_report(y_test, y_pred)

print(mnb_cfm)
print(mnb_sum)
print(f"✅ Accuracy (with Attacut): {mnb_score:.4f}")

[[12  1]
 [ 0 13]]
              precision    recall  f1-score   support

         neg       1.00      0.92      0.96        13
         pos       0.93      1.00      0.96        13

    accuracy                           0.96        26
   macro avg       0.96      0.96      0.96        26
weighted avg       0.96      0.96      0.96        26

✅ Accuracy (with Attacut): 0.9615


In [52]:
with open('best_model_attacut.pkl', 'wb') as f:
    pickle.dump((vectorizer, multi_nb), f)

sea614ml-3fgcfse4jugkjhhpcg4ae5